name: 'streamify-nats'

services:
  reader:
    image: nats-reader
    build:
      context: ../../read-work-write
      dockerfile: ./Dockerfile    
    depends_on:
      - nats   
    volumes:
      - ./../../temp:/home/node/temp
    network_mode: host
    environment:
      NODE_ENV: production
    command: ["--verbose", "../temp/sample.txt", "nats:4222/file-transfer"]
  writer:
    image: nats-writer
    build:
      context: ../../read-work-write
      dockerfile: ./Dockerfile   
    depends_on:
      - nats
    volumes:
      - ./../../temp:/home/node/temp
    environment:
      NODE_ENV: production
    network_mode: host
    command: ["--verbose", "nats:4222/file-transfer", "../temp/copy-over-nats.txt", "-w slow"]
  nats:
    image: nats:2.10.14-alpine3.19 # https://github.com/nats-io/nats-docker/blob/main/2.10.x/alpine3.19/
    ports:
      - 8222:8222
      - 4222:4222
