name: 'streamify-csv-debug'

services:
  csv2obj:
    image: csv2obj
    build:
      context: ../../streamify
      dockerfile: ./Dockerfile
      target: development       
    volumes:
      - ./../../streamify:/home/node/app
      - ./temp:/home/node/temp
    environment:
      NODE_ENV: development
      DEBUG: '*'   
    network_mode: host
    # command: ["run", "start:debug", "--", "--", "../temp/sample.txt", "../temp/copy.txt"]
    command: [
      "run", 
      "start:debug", 
      "--", "--", 
      "../temp/chord-progressions.csv", 
      "-from csv-parse:parse:(delimiter=,)", # we're using https://csv.js.org/parse/examples/stream_pipe/
      "-w row2obj",
      "-w aggregate",
      "-m generate-a-song",
      "-w extract:prompt",
      #"-m some-song-generation-api",
      "../temp/last-prompt.txt", 
      "--verbose"
      ]
